export const SET_NMRIUM_DATA = 'SET_NMRIUM_DATA';
export const SET_RESULT_DATA = 'SET_RESULT_DATA';
export const CLEAR_RESULT_DATA = 'CLEAR_RESULT_DATA';
export const EDIT_FORBIDDEN_NEIGHBORS = 'EDIT_FORBIDDEN_NEIGHBORS';
export const EDIT_SET_NEIGHBORS = 'EDIT_SET_NEIGHBORS';
export const EDIT_FIXED_NEIGHBORS = 'EDIT_FIXED_NEIGHBORS';
export const EDIT_HYBRIDIZATIONS = 'EDIT_HYBRIDIZATIONS';
export const SET_RESULT_DB_ENTRIES = 'SET_RESULT_DB_ENTRIES';
