export const SET_NMRIUM_DATA = 'SET_NMRIUM_DATA';
export const SET_RESULT_DATA = 'SET_RESULT_DATA';
export const CLEAR_MOLECULES = 'CLEAR_MOLECULES';
export const EDIT_FORBIDDEN_NEIGHBORS = 'EDIT_FORBIDDEN_NEIGHBORS';
export const EDIT_SET_NEIGHBORS = 'EDIT_SET_NEIGHBORS';
export const EDIT_HYBRIDIZATIONS = 'EDIT_HYBRIDIZATIONS';
